# Generated by Django 5.0 on 2023-12-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal', '0002_alter_article_options_alter_monument_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monument',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='monument',
            name='foundation_date',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Дата заснування'),
        ),
    ]
