# Generated by Django 5.0 on 2023-12-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal', '0003_remove_monument_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monument',
            name='foundation_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата заснування'),
        ),
    ]
