# Generated by Django 5.0 on 2023-12-17 05:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'публікація', 'verbose_name_plural': 'публікації'},
        ),
        migrations.AlterModelOptions(
            name='monument',
            options={'verbose_name': 'монумент', 'verbose_name_plural': 'монументи'},
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Зображення'),
        ),
        migrations.AddField(
            model_name='monument',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='monuments/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='article',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редагування'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='monument',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='monument',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='monument',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='monument',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Локація'),
        ),
        migrations.AlterField(
            model_name='monument',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Довгота'),
        ),
        migrations.AlterField(
            model_name='monument',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата модифікації'),
        ),
        migrations.AlterField(
            model_name='monument',
            name='monument_type',
            field=models.CharField(choices=[('art', 'Мистецство'), ('history', 'Історія'), ('architecture', 'Архітектура'), ('archeology', 'Археологія'), ('reservation', 'Заповідник')], max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='monument',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Назва'),
        ),
    ]
