# Generated by Django 5.0 on 2024-05-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal', '0005_alter_monument_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monument',
            name='monument_type',
            field=models.CharField(choices=[('art', 'Мистецтво'), ('history', 'Історія'), ('architecture', 'Архітектура'), ('archeology', 'Археологія'), ('reservation', 'Заповідник')], max_length=50, verbose_name='Тип'),
        ),
    ]
